### PR TITLE
Build in release mode for smaller libraries and executables

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by iainrussell** [comment]
Oops, looks like I don't have write access to this repo - could someone merge this for me please?
Thanks!

**Comment by dtip** [comment]
@conda-forge-admin, please rerender

**Comment by dtip** [comment]
@iainrussell I assume you're happy to be a maintainer here?

**Comment by iainrussell** [comment]
Absolutely @dtip , that would make things easier!

**Comment by iainrussell** [comment]
Many thanks!

**Pull request merged**
